version: "2"

services:

  app:
    image: cyj-chapter:1.0.2
    ports:
      - "80:80"
    env_file: ./.env
    restart: always

  postgres:
    image: postgres:14.5
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
